quadratic:
  gradient_descent:
    x0: null
    grad: False
    hessian: False
    max_iters: 5000
    delta1: 1.0e-7
    delta2: 1.0e-5
    alpha: 4

  newton_method:
    x0: null
    grad: True
    hessian: True
    max_iters: 5000
    delta1: 1.0e-7
    delta2: 1.0e-5
    alpha: 4

  quasi_newton_method:
    x0: null
    grad: True
    hessian: False
    max_iters: 5000
    delta1: 1.0e-7
    delta2: 1.0e-5
    alpha: 4

  adam_optimizer:
    x0: null
    grad: False
    hessian: False
    max_iters: 5000
    delta1: 1.0e-7
    delta2: 1.0e-5
    alpha: 4

log:
  gradient_descent:
    x0: null
    grad: True
    hessian: False
    max_iters: 5000
    delta1: 1.0e-7
    delta2: 1.0e-5
    alpha: 1

  newton_method:
    x0: null
    grad: True
    hessian: True
    max_iters: 5000
    delta1: 1.0e-7
    delta2: 1.0e-5
    alpha: 1

  quasi_newton_method:
    x0: null
    grad: True
    hessian: False
    max_iters: 5000
    delta1: 1.0e-7
    delta2: 1.0e-5
    alpha: 1

  adam_optimizer:
    x0: null
    grad: True
    hessian: False
    max_iters: 5000
    delta1: 1.0e-7
    delta2: 1.0e-5
    alpha: 0.9

bi_quadratic:
  gradient_descent:
    x0: [2, 2]
    grad: True
    hessian: False
    max_iters: 5000
    delta1: 1.0e-7
    delta2: 1.0e-7
    alpha: 1

  newton_method:
    x0: [2, 2]
    grad: True
    hessian: True
    max_iters: 5000
    delta1: 1.0e-7
    delta2: 1.0e-7
    alpha: 1

  quasi_newton_method:
    x0: [2, 2]
    grad: True
    hessian: False
    max_iters: 5000
    delta1: 1.0e-7
    delta2: 1.0e-7
    alpha: 1

  adam_optimizer:
    x0: [2, 2]
    grad: True
    hessian: False
    max_iters: 5000
    delta1: 1.0e-7
    delta2: 1.0e-7
    alpha: 0.3
    use_line_search: False
